name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'
          - '2022.02'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Linux specific setup
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libxml2-dev
      - name: Install Dependencies
        run: |
          zef install --/test LibraryMake
          zef install App::Prove6
          zef install --deps-only .
          zef build .
      - name: Run Tests
        run: prove6 -I .  t
